# Generated by Django 2.1.7 on 2019-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sum_total',
            field=models.IntegerField(default=0),
        ),
    ]
